In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix

In [2]:
labels = pd.read_csv('labels.csv')
labels.head()

perfect_labeler radiologist  algorithm
0          cancer      cancer       0.99
1          cancer      cancer       0.94
2          cancer      cancer       0.73
3          cancer      cancer       0.82
4          cancer      cancer       0.98

In [4]:
radiologist_accuracy = sum(labels.perfect_labeler == labels.radiologist)/len(labels)
radiologist_accuracy

0.8993288590604027

In [5]:
confusion_matrix(labels.perfect_labeler.values, labels.radiologist.values, labels=['cancer', 'benign'])

array([[ 25,   4],
       [ 11, 109]])

In [6]:
labels = labels.replace('cancer', 1).replace('benign', 0)
labels.head()

perfect_labeler  radiologist  algorithm
0                1            1       0.99
1                1            1       0.94
2                1            1       0.73
3                1            1       0.82
4                1            1       0.98

In [7]:
probability_cutoff = (labels.algorithm > 0.5)
confusion_matrix(labels.perfect_labeler, probability_cutoff, labels=[1, 0])

array([[ 21,   8],
       [  8, 112]])

In [8]:
probability_cutoff = (labels.algorithm > 0.4)
confusion_matrix(labels.perfect_labeler, probability_cutoff, labels=[1, 0])

array([[ 25,   4],
       [ 16, 104]])

In [9]:
probability_cutoff = (labels.algorithm > 0.6)
confusion_matrix(labels.perfect_labeler, probability_cutoff, labels=[1, 0])

array([[ 20,   9],
       [  5, 115]])

In [10]:
probability_cutoff = (labels.algorithm > 0.5)
confusion_matrix(labels.radiologist, probability_cutoff, labels=[1, 0])

array([[ 23,  13],
       [  6, 107]])